[package]
name = "ass4"
version = "0.1.0"
authors = ["hp"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[lib]
name= "calculator"
path= "src/lib.rs"
